package io.circuitdrift.androidialup.protocol;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Cross-language golden vectors generated by prototype/python/tools/gen_adup_vectors.py.
 * Format: one vector per line, {@code name<TAB>kind_int<TAB>hex}. Lines starting with '#'
 * and blank lines are ignored. Names prefixed {@code frame.} hold a complete ADUP frame.
 */
class PayloadCodecVectorsTest {
    private static final String RELATIVE = "prototype/python/tests/vectors/adup_v1_vectors.txt";

    record Vector(String name, int kind, byte[] bytes) {}

    private static List<Vector> vectors;

    @BeforeAll
    static void load() throws IOException {
        File file = locate();
        assertNotNull(file, "could not locate " + RELATIVE + " from " + System.getProperty("user.dir"));
        List<Vector> out = new ArrayList<>();
        for (String line : Files.readAllLines(file.toPath(), StandardCharsets.UTF_8)) {
            if (line.isBlank() || line.startsWith("#")) continue;
            String[] parts = line.split("\t", -1);
            assertEquals(3, parts.length, "malformed vector line: " + line);
            out.add(new Vector(parts[0], Integer.parseInt(parts[1]), hex(parts[2])));
        }
        assertFalse(out.isEmpty());
        vectors = out;
    }

    private static File locate() {
        File dir = new File(System.getProperty("user.dir")).getAbsoluteFile();
        // Gradle project dir is android/core-protocol, so ../../ reaches the repo root; fall back to walking up.
        File direct = new File(dir, "../../" + RELATIVE);
        if (direct.isFile()) return direct;
        for (File d = dir; d != null; d = d.getParentFile()) {
            File candidate = new File(d, RELATIVE);
            if (candidate.isFile()) return candidate;
        }
        return null;
    }

    private static byte[] hex(String s) {
        byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) out[i] = (byte) Integer.parseInt(s.substring(2 * i, 2 * i + 2), 16);
        return out;
    }

    private static byte[] fill(int n, char c) {
        byte[] out = new byte[n];
        java.util.Arrays.fill(out, (byte) c);
        return out;
    }

    private static Vector find(String name) {
        for (Vector v : vectors) if (v.name().equals(name)) return v;
        throw new AssertionError("missing vector " + name);
    }

    @Test
    void everyPayloadVectorRoundTripsToIdenticalBytes() {
        int count = 0;
        for (Vector v : vectors) {
            if (v.name().startsWith("frame.")) continue;
            FrameKind kind = FrameKind.fromValue(v.kind());
            AduMessage message = PayloadCodec.decode(kind, v.bytes());
            assertEquals(kind, PayloadCodec.kindFor(message), v.name());
            assertArrayEquals(v.bytes(), PayloadCodec.encode(message), v.name());
            assertEquals(message, PayloadCodec.decode(kind, v.bytes()), v.name());
            count++;
        }
        assertTrue(count >= 19, "expected at least one vector per message type, got " + count);
    }

    @Test
    void everyFrameVectorRoundTripsToIdenticalBytes() {
        int count = 0;
        for (Vector v : vectors) {
            if (!v.name().startsWith("frame.")) continue;
            FrameCodec.Decoded decoded = FrameCodec.decode(v.bytes(), FrameCodec.MAX_PAYLOAD);
            assertEquals(v.bytes().length, decoded.bytesConsumed(), v.name());
            AduFrame frame = decoded.frame();
            assertEquals(v.kind(), frame.kind().value(), v.name());
            AduMessage message = PayloadCodec.decode(frame.kind(), frame.payload());
            AduFrame rebuilt = new AduFrame(PayloadCodec.kindFor(message), frame.flags(), frame.callId(),
                    frame.sessionId(), frame.requestId(), PayloadCodec.encode(message));
            assertArrayEquals(v.bytes(), FrameCodec.encode(rebuilt), v.name());
            // the stream decoder must agree with the one-shot decoder
            assertEquals(List.of(frame), new FrameStreamDecoder().feed(v.bytes()), v.name());
            count++;
        }
        assertTrue(count >= 1);
    }

    @Test
    void everyMessageKindIsCovered() {
        for (FrameKind kind : FrameKind.values()) {
            if (kind.value() >= 60) continue; // incoming-call kinds are reserved, no payload codec yet
            boolean covered = vectors.stream().anyMatch(v -> v.kind() == kind.value() && !v.name().startsWith("frame."));
            assertTrue(covered, "no vector for " + kind);
        }
    }

    @Test
    void helloVectorDecodesExpectedFields() {
        Vector v = find("hello.basic");
        Hello hello = (Hello) PayloadCodec.decode(FrameKind.HELLO, v.bytes());
        assertEquals("AndroidDialup", hello.clientName());
        assertEquals("0.1", hello.clientVersion());
        assertEquals(1, hello.protocolMin());
        assertEquals(1, hello.protocolMax());
        assertArrayEquals(fill(32, 'E'), hello.endpointId());
        assertEquals(List.of("BYTE_RELAY", "PCM_VBD_EXPERIMENTAL"), hello.capabilities());
    }

    @Test
    void dialRequestVectorDecodesExpectedFields() {
        Vector v = find("dial_request.basic");
        DialRequest req = (DialRequest) PayloadCodec.decode(FrameKind.DIAL_REQUEST, v.bytes());
        assertEquals("loopback", req.target());
        assertEquals(Mode.BYTE_RELAY, req.requestedMode());
        assertEquals(ProtocolTransport.WIFI, req.networkTransport());
        assertEquals(List.of("BYTE_RELAY"), req.clientCapabilities());
        assertEquals(60000L, req.dialTimeoutMs());
        assertEquals(List.of(Map.entry("test", "1")), req.callerMetadata());
    }

    @Test
    void nonAsciiAndOptionalVectorsDecodeExpectedFields() {
        var utf8 = (HelloReject) PayloadCodec.decode(FrameKind.HELLO_REJECT, find("hello_reject.utf8").bytes());
        assertEquals("é€😀 日本語", utf8.reason());

        var withDetail = (DialFailed) PayloadCodec.decode(FrameKind.DIAL_FAILED, find("dial_failed.with_detail").bytes());
        assertEquals(DialFailure.BUSY, withDetail.reason());
        assertFalse(withDetail.retryable());
        assertEquals("busy", withDetail.humanDetail());
        assertArrayEquals(fill(16, 'C'), withDetail.callId());

        var noDetail = (DialFailed) PayloadCodec.decode(FrameKind.DIAL_FAILED, find("dial_failed.no_detail").bytes());
        assertEquals(DialFailure.TIMEOUT, noDetail.reason());
        assertTrue(noDetail.retryable());
        assertNull(noDetail.humanDetail());

        var progress = (CallProgress) PayloadCodec.decode(FrameKind.CALL_PROGRESS, find("call_progress.no_detail").bytes());
        assertEquals(ProgressPhase.RINGBACK, progress.phase());
        assertNull(progress.detail());
    }

    @Test
    void unsignedAndSizedVectorsDecodeExpectedFields() {
        var ping = (Ping) PayloadCodec.decode(FrameKind.PING, find("ping.max_u64").bytes());
        assertEquals(-1L, ping.nonce());
        assertEquals(Long.MIN_VALUE, ping.monotonicHint());
        var flow = (FlowStatus) PayloadCodec.decode(FrameKind.FLOW_STATUS, find("flow_status.max_u32").bytes());
        assertEquals(0xffff_ffffL, flow.receiveWindowBytes());
        assertEquals(0xffff_ffffL, flow.queuedBytes());
        var data = (DataBytes) PayloadCodec.decode(FrameKind.DATA_BYTES, find("data_bytes.max").bytes());
        assertEquals(MessageLimits.MAX_DATA_BYTES, data.data().length);
        var ack = (HelloAck) PayloadCodec.decode(FrameKind.HELLO_ACK, find("hello_ack.max_capabilities").bytes());
        assertEquals(MessageLimits.MAX_CAPABILITIES, ack.capabilities().size());
        var ok = (AuthOk) PayloadCodec.decode(FrameKind.AUTH_OK, find("auth_ok.max_policy").bytes());
        assertEquals(MessageLimits.MAX_MAP_ENTRIES, ok.policy().size());
        var resp = (AuthResponse) PayloadCodec.decode(FrameKind.AUTH_RESPONSE, find("auth_response.max_blob").bytes());
        assertEquals(MessageLimits.MAX_BLOB, resp.proof().length);
    }

    @Test
    void frameVectorDecodesExpectedHeaderFields() {
        Vector v = find("frame.dial_accepted");
        AduFrame frame = FrameCodec.decode(v.bytes(), FrameCodec.MAX_PAYLOAD).frame();
        assertEquals(FrameKind.DIAL_ACCEPTED, frame.kind());
        assertEquals(0x0001, frame.flags());
        assertEquals(0x01020304L, frame.requestId());
        assertArrayEquals(fill(16, 'C'), frame.callId());
        assertArrayEquals(fill(16, 'S'), frame.sessionId());
        var accepted = (DialAccepted) PayloadCodec.decode(frame.kind(), frame.payload());
        assertEquals("gw-loopback", accepted.selectedGatewayId());
        assertEquals(Mode.BYTE_RELAY, accepted.selectedMode());
    }
}
