package io.circuitdrift.androidialup.protocol;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Cross-language golden vectors generated by prototype/python/tools/gen_adup_vectors.py.
 * Format: one vector per line, {@code name<TAB>kind_int<TAB>hex}. Lines starting with '#'
 * and blank lines are ignored. Names prefixed {@code frame.} hold a complete ADUP frame.
 */
class PayloadCodecVectorsTest {
    private static final String RELATIVE = "prototype/python/tests/vectors/adup_v1_vectors.txt";

    record Vector(String name, int kind, byte[] bytes) {}

    private static List<Vector> vectors;

    @BeforeAll
    static void load() throws IOException {
        File file = locate();
        assertNotNull(file, "could not locate " + RELATIVE + " from " + System.getProperty("user.dir"));
        List<Vector> out = new ArrayList<>();
        for (String line : Files.readAllLines(file.toPath(), StandardCharsets.UTF_8)) {
            if (line.isBlank() || line.startsWith("#")) continue;
            String[] parts = line.split("\t", -1);
            assertEquals(3, parts.length, "malformed vector line: " + line);
            out.add(new Vector(parts[0], Integer.parseInt(parts[1]), hex(parts[2])));
        }
        assertFalse(out.isEmpty());
        vectors = out;
    }

    private static File locate() {
        File dir = new File(System.getProperty("user.dir")).getAbsoluteFile();
        // Gradle project dir is android/core-protocol, so ../../ reaches the repo root; fall back to walking up.
        File direct = new File(dir, "../../" + RELATIVE);
        if (direct.isFile()) return direct;
        for (File d = dir; d != null; d = d.getParentFile()) {
            File candidate = new File(d, RELATIVE);
            if (candidate.isFile()) return candidate;
        }
        return null;
    }

    private static byte[] hex(String s) {
        byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) out[i] = (byte) Integer.parseInt(s.substring(2 * i, 2 * i + 2), 16);
        return out;
    }



    @Test
    void everyPayloadVectorRoundTripsToIdenticalBytes() {
        int count = 0;
        for (Vector v : vectors) {
            if (v.name().startsWith("frame.")) continue;
            FrameKind kind = FrameKind.fromValue(v.kind());
            Messages.Message message = PayloadCodec.decode(kind, v.bytes());
            assertEquals(kind, PayloadCodec.kindFor(message), v.name());
            assertArrayEquals(v.bytes(), PayloadCodec.encode(message), v.name());
            assertEquals(message, PayloadCodec.decode(kind, v.bytes()), v.name());
            count++;
        }
        assertTrue(count >= 19, "expected at least one vector per message type, got " + count);
    }

    @Test
    void everyFrameVectorRoundTripsToIdenticalBytes() {
        int count = 0;
        for (Vector v : vectors) {
            if (!v.name().startsWith("frame.")) continue;
            FrameCodec.Decoded decoded = FrameCodec.decode(v.bytes(), FrameCodec.MAX_PAYLOAD);
            assertEquals(v.bytes().length, decoded.bytesConsumed(), v.name());
            AduFrame frame = decoded.frame();
            assertEquals(v.kind(), frame.kind().value(), v.name());
            Messages.Message message = PayloadCodec.decode(frame.kind(), frame.payload());
            AduFrame rebuilt = new AduFrame(PayloadCodec.kindFor(message), frame.flags(), frame.callId(),
                    frame.sessionId(), frame.requestId(), PayloadCodec.encode(message));
            assertArrayEquals(v.bytes(), FrameCodec.encode(rebuilt), v.name());
            // the stream decoder must agree with the one-shot decoder
            assertEquals(List.of(frame), new FrameStreamDecoder().feed(v.bytes()), v.name());
            count++;
        }
        assertTrue(count >= 1);
    }

    @Test
    void everyMessageKindIsCovered() {
        for (FrameKind kind : FrameKind.values()) {
            if (kind.value() >= 60) continue; // incoming-call kinds are reserved, no payload codec yet
            boolean covered = vectors.stream().anyMatch(v -> v.kind() == kind.value() && !v.name().startsWith("frame."));
            assertTrue(covered, "no vector for " + kind);
        }
    }
}
