pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'androidialup-android'
include 'core-network'
include 'core-protocol'
include 'core-modem'
include 'core-session'
include 'platform-android'
include 'app'
